# Generated by Django 3.2.5 on 2021-07-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
