# Generated by Django 3.2.5 on 2021-07-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0003_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='user',
            new_name='planned_by',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='users',
            new_name='user_who_join',
        ),
    ]
